import { test, expect, selectText, middleClick } from './fixtures.js';

test('Custom search and Custom AI save independently and route the selection or full prompt', async ({ extension, page }) => {
  const options = await extension.context.newPage();
  await options.goto(`chrome-extension://${extension.id}/options.html`);
  await expect(options.locator('#controls')).toBeEnabled();
  await expect(options.locator('option[value=custom]')).toHaveText('Custom search');
  await options.locator('#enginePreset').selectOption('custom');
  const search = `${extension.baseUrl}/find?q=%s`;
  await options.locator('#searchEngine').fill(search);
  await options.locator('#save').click();
  await expect(options.locator('#status')).toHaveText('Preferences saved.');
  await options.locator('#enginePreset').selectOption('custom-ai');
  await expect(options.locator('#customAi')).toBeVisible();
  await expect(options.locator('#customEngine')).toBeHidden();
  await expect(options.locator('#autoSendOption')).toBeHidden();
  await options.locator('#customAiUrl').fill(`${extension.baseUrl}/chat?prompt=%s`);
  await options.locator('#aiPrompt').fill('Discuss {text}\nFrom Page: {url}');
  await options.locator('#save').click();
  await expect(options.locator('#status')).toHaveText('Preferences saved.');
  await options.reload();
  await expect(options.locator('#enginePreset')).toHaveValue('custom-ai');
  await expect(options.locator('#customAiUrl')).toHaveValue(`${extension.baseUrl}/chat?prompt=%s`);
  await page.bringToFront();
  await selectText(page, 'café & {url} %s');
  const ai = await middleClick(extension, page);
  expect(new URL(ai.url()).searchParams.get('prompt')).toBe(`Discuss café & {url} %s\nFrom Page: ${page.url()}`);
  expect(new URL(ai.url()).hash).toBe('');
  const popup = await extension.context.newPage();
  await popup.goto(`chrome-extension://${extension.id}/popup.html`);
  await expect(popup.locator('#enginePreset')).toHaveValue('custom-ai');
  await expect(popup.locator(`option[value="${search}"]`)).toHaveText('Custom search');
  await popup.locator('#enginePreset').selectOption(search);
  await expect(popup.locator('#enginePreset')).toHaveValue(search);
  await page.bringToFront();
  await selectText(page, 'plain search');
  const result = await middleClick(extension, page);
  expect(new URL(result.url()).searchParams.get('q')).toBe('plain search');
  await popup.locator('#enginePreset').selectOption('custom-ai');
  await options.reload();
  await expect(options.locator('#customAiUrl')).toHaveValue(`${extension.baseUrl}/chat?prompt=%s`);
});

test('Custom AI validation prevents invalid saves and does not block other destinations', async ({ extension }) => {
  const page = await extension.context.newPage();
  await page.goto(`chrome-extension://${extension.id}/options.html`);
  await expect(page.locator('#controls')).toBeEnabled();
  await page.locator('#enginePreset').selectOption('custom-ai');
  await page.locator('#customAiUrl').fill('javascript:%s');
  await expect(page.locator('#custom-ai-error')).toContainText('HTTP or HTTPS');
  await page.locator('#save').click();
  expect((await extension.worker.evaluate(() => chrome.storage.sync.get('destination'))).destination).not.toBe('custom-ai');
  await page.locator('#customAiUrl').fill('https://example.test/');
  await expect(page.locator('#custom-ai-error')).toContainText('%s');
  await page.locator('#enginePreset').selectOption('chatgpt');
  await page.locator('#save').click();
  await expect(page.locator('#status')).toHaveText('Preferences saved.');
  await page.locator('#enginePreset').selectOption('custom-ai');
  await page.locator('#customAiUrl').fill('http://localhost:1234/?prompt=%s');
  await page.locator('#save').click();
  await expect(page.locator('#status')).toHaveText('Preferences saved.');
  await page.locator('#customAiUrl').fill('javascript:%s');
  await page.locator('#enginePreset').selectOption('chatgpt');
  await page.locator('#save').click();
  await expect(page.locator('#status')).toHaveText('Preferences saved.');
  expect((await extension.worker.evaluate(() => chrome.storage.sync.get('customAiUrl'))).customAiUrl).toBe('http://localhost:1234/?prompt=%s');
  await page.locator('#reset').click();
  await expect(page.locator('#status')).toHaveText('Preferences saved.');
  await expect(page.locator('#customAiUrl')).toHaveValue('');
});
